import fs from 'fs/promises';
import path from 'path';
import * as url from "node:url";


function toCamelCase(str) {
    // 将下划线和中划线统一替换为空格
    let camelCaseStr = str.replace(/[-_]/g, ' ');

    // 将每个单词的首字母大写，其余字母小写
    camelCaseStr = camelCaseStr.split(' ').map(word => {
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    }).join('');

    return camelCaseStr;
}

// 读取所有的icon
const basePath = path.resolve(url.fileURLToPath(import.meta.url), '../../src/assets/icons')

// 读取所有的svg
const icons = await fs.readdir(basePath)

const assets = icons.map(it => ({
    componentName: toCamelCase(it.slice(0, -path.extname(it).length)) + "Icon",
    filePath: `@/assets/icons/${it}`,
    name: it.slice(0, -path.extname(it).length)
}))

let scriptTemplate = `// This file is generated by generate-assets.mjs. DO NOT MODIFY.
import React from "react";
import { SvgProps } from "react-native-svg";
import { toSvgColor } from "@/utils/svgColor";

${assets.map(asset => `import ${asset.componentName} from "${asset.filePath}";`).join('\n')}

export type IIconName =
${assets.map(asset => `    | "${asset.name}"`).join("\n")};

interface IProps extends SvgProps {
    /** 图标名称 */
    name: IIconName;
    /** 图标大小 */
    size?: number;
}

const iconMap = {
${assets.map(asset => `    "${asset.name}": ${asset.componentName},`).join("\n")}
} as const;

export default function Icon(props: IProps) {
    const { name, size, color } = props;
    const svgColor = toSvgColor(color as string | number | undefined, "rgba(0,0,0,1)");

    const newProps = {
        ...props,
        color: svgColor,
        width: props.width ?? size,
        height: props.height ?? size,
    } as SvgProps;

    const Component = iconMap[name];

    if (!Component) {
        return null;
    }

    const iconKey = \`\${name}-\${String(color ?? "default")}\`;

    return <Component key={iconKey} {...newProps} />;
}
`

const targetPath = path.resolve(url.fileURLToPath(import.meta.url), '../../src/components/base/icon.tsx');
await fs.writeFile(targetPath, scriptTemplate, 'utf8');

console.log(`Generate Succeed. ${assets.length} assets.`)
